In [3]:
import numpy as np
import pandas as pd

In [4]:
outfits = pd.read_csv('Ajio_Men_Clothing_Updated.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Ajio_Men_Clothing_Updated.csv'

In [ ]:
# Brand Description Id_Product Color
outfits = outfits[['Id_Product', 'Brand', 'Description', 'Color', 'Category']]

outfits.head()

,Id_Product,Brand,Description,Color,Category
0,441137362002,netplay,Checked Polo T-shirt,white,Polo T-shirt
1,441124497006,netplay,Tapered Fit Flat-Front Trousers,navy,Trousers
2,460453612003,the-indian-garage-co,Striped Slim Fit Shirt with Patch Pocket,white,Slim Fit Shirt
3,441036730003,performax,Heathered Crew-Neck T-shirt,charcoal,T-shirt
4,441128531011,john-players-jeans,Washed Skinny Fit Jeans with Whiskers,jetblack,Jeans

In [ ]:
outfits['Description'] = outfits['Description'].apply(lambda x:x.split())

In [ ]:
outfits.head()

,Id_Product,Brand,Description,Color,Category
0,441137362002,netplay,"[Checked, Polo, T-shirt]",white,Polo T-shirt
1,441124497006,netplay,"[Tapered, Fit, Flat-Front, Trousers]",navy,Trousers
2,460453612003,the-indian-garage-co,"[Striped, Slim, Fit, Shirt, with, Patch, Pocket]",white,Slim Fit Shirt
3,441036730003,performax,"[Heathered, Crew-Neck, T-shirt]",charcoal,T-shirt
4,441128531011,john-players-jeans,"[Washed, Skinny, Fit, Jeans, with, Whiskers]",jetblack,Jeans

In [ ]:
outfits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18919 entries, 0 to 18918
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id_Product   18919 non-null  int64
 1   Brand        18919 non-null  object
 2   Description  18919 non-null  object
 3   Color        18919 non-null  object
 4   Category     18919 non-null  object
dtypes: int64(1), object(4)
memory usage: 739.2+ KB

In [ ]:
outfits['Category'] = outfits['Category'].apply(lambda x: x.replace(" ", ""))

In [ ]:
outfits.head()

,Id_Product,Brand,Description,Color,Category
0,441137362002,netplay,"[Checked, Polo, T-shirt]",white,PoloT-shirt
1,441124497006,netplay,"[Tapered, Fit, Flat-Front, Trousers]",navy,Trousers
2,460453612003,the-indian-garage-co,"[Striped, Slim, Fit, Shirt, with, Patch, Pocket]",white,SlimFitShirt
3,441036730003,performax,"[Heathered, Crew-Neck, T-shirt]",charcoal,T-shirt
4,441128531011,john-players-jeans,"[Washed, Skinny, Fit, Jeans, with, Whiskers]",jetblack,Jeans

In [ ]:
outfits['Category'].apply(lambda x:[i.replace(" ","") for i in x])

0           [Polo, T-shirt]
1                [Trousers]
2        [Slim, Fit, Shirt]
3                 [T-shirt]
4                   [Jeans]
                ...
18914    [Slim, Fit, Shirt]
18915    [Slim, Fit, Shirt]
18916    [Printed, T-shirt]
18917    [Printed, T-shirt]
18918             [Joggers]
Name: Category, Length: 18919, dtype: object

In [ ]:
outfits['tags'] = outfits.apply(lambda row: [row['Brand']] + row['Description'] + [row['Color']] + [row['Category']], axis=1)

In [ ]:
outfits.head()

,Id_Product,Brand,Description,Color,Category,tags
0,441137362002,netplay,"[Checked, Polo, T-shirt]",white,PoloT-shirt,"[netplay, Checked, Polo, T-shirt, white, PoloT..."
1,441124497006,netplay,"[Tapered, Fit, Flat-Front, Trousers]",navy,Trousers,"[netplay, Tapered, Fit, Flat-Front, Trousers, ..."
2,460453612003,the-indian-garage-co,"[Striped, Slim, Fit, Shirt, with, Patch, Pocket]",white,SlimFitShirt,"[the-indian-garage-co, Striped, Slim, Fit, Shi..."
3,441036730003,performax,"[Heathered, Crew-Neck, T-shirt]",charcoal,T-shirt,"[performax, Heathered, Crew-Neck, T-shirt, cha..."
4,441128531011,john-players-jeans,"[Washed, Skinny, Fit, Jeans, with, Whiskers]",jetblack,Jeans,"[john-players-jeans, Washed, Skinny, Fit, Jean..."

In [ ]:
df = outfits[['Id_Product', 'tags']]

In [ ]:
df.head()

     Id_Product                                               tags
0  441137362002  [netplay, Checked, Polo, T-shirt, white, PoloT...
1  441124497006  [netplay, Tapered, Fit, Flat-Front, Trousers, ...
2  460453612003  [the-indian-garage-co, Striped, Slim, Fit, Shi...
3  441036730003  [performax, Heathered, Crew-Neck, T-shirt, cha...
4  441128531011  [john-players-jeans, Washed, Skinny, Fit, Jean...

In [ ]:
df['tags'] = df['tags'].apply(lambda x:" ".join(x))

C:\Users\asus\AppData\Local\Temp\ipykernel_21400\4267108141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x:" ".join(x))

In [ ]:
df['tags'] = df['tags'].apply(lambda x:x.lower())

C:\Users\asus\AppData\Local\Temp\ipykernel_21400\841579467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x:x.lower())

In [ ]:
df.head()

     Id_Product                                               tags
0  441137362002     netplay checked polo t-shirt white polot-shirt
1  441124497006  netplay tapered fit flat-front trousers navy t...
2  460453612003  the-indian-garage-co striped slim fit shirt wi...
3  441036730003  performax heathered crew-neck t-shirt charcoal...
4  441128531011  john-players-jeans washed skinny fit jeans wit...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vectors = cv.fit_transform(df['tags']).toarray()

In [ ]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
cv.get_feature_names_out()

array(['000', '0001', '0008', ..., 'zorro', 'zrn', 'zw4'], dtype=object)

In [ ]:
import nltk

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [ ]:
df['tags'].apply(stem)

0             netplay check polo t-shirt white polot-shirt
1        netplay taper fit flat-front trouser navi trouser
2        the-indian-garage-co stripe slim fit shirt wit...
3        performax heather crew-neck t-shirt charcoal t...
4        john-players-jean wash skinni fit jean with wh...
                               ...
18914    louis-philipp check shirt with patch pocket wh...
18915    brooks-broth shirt with button-down collar 55 ...
18916    spykar albert einstein print slim fit crew-nec...
18917    jockey print crew-neck t-shirt navyblu printed...
18918    max typograph print jogger with elast waist bl...
Name: tags, Length: 18919, dtype: object

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vectors)

array([[1.        , 0.11111111, 0.31622777, ..., 0.35634832, 0.42163702,
        0.        ],
       [0.11111111, 1.        , 0.10540926, ..., 0.08908708, 0.        ,
        0.        ],
       [0.31622777, 0.10540926, 1.        , ..., 0.3380617 , 0.2       ,
        0.        ],
       ...,
       [0.35634832, 0.08908708, 0.3380617 , ..., 1.        , 0.59160798,
        0.08451543],
       [0.42163702, 0.        , 0.2       , ..., 0.59160798, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.08451543, 0.        ,
        1.        ]])

In [ ]:
similarity = cosine_similarity(vectors)

In [ ]:
similarity[0]

array([1.        , 0.11111111, 0.31622777, ..., 0.35634832, 0.42163702,
       0.        ])

In [ ]:
import numpy as np

# Save the similarity matrix to a .npy file
np.save('similarity_matrix.npy', similarity)

# To load the similarity matrix from the .npy file
similarity = np.load('similarity_matrix.npy')

:

In [ ]:
def recommend(outfit):
    outfit_indices = df[df['Id_Product'] == outfit].index

    # If outfit is not found, print a message and return
    if outfit_indices.empty:
        print(f"Outfit with Id_Product '{outfit}' not found.")
        return

    # Get the first index of the outfit
    outfit_index = outfit_indices[0]
    
    # Calculate the distances
    distances = similarity[outfit_index]

    # Get a list of tuples (index, distance), sorted by distance in descending order
    outfits_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:70]

    # Print the recommended outfit indices
    for i in outfits_list:
        print(df.iloc[i[0]].Id_Product)

In [ ]:
recommend(441137362002)

441114668001
441128325006
441137355005
441137364025
441024764004
441120096001
441113170001
441117495007
441135711005
441120431010
441125682001
441120429010
441125682006
441118434001
441137067015
441114668006
441118335004
441128325013
441118353002
441137366010
441136043004
441024764042
441137365015
441024764024
441124240001
441136043016
460849982002
441115601001
464281459004
463543030003
463731625001
460996019003
460899186004
441120068023
463731622006
460793091002
441135713013
464301895010
463731614005
464281458003
441137371008
460968030003
463731628006
463731631006
460582759002
469080226004
441120433006
441126461011
441134733019
441134734005
441137364003
441128327005
441127190003
441120432001
469080334005
441134730005
441126569006
441024764010
441137356001
441024764028
441024764055
441024764036
441024764049
461561319003
441136044004
441137367006
441135322006
441136044019
441137360007